version: '3.7'
services:

    frontend:
      build:
        context: ./app-frontend
      restart: always
      ports:
        - "3000:3000"
      working_dir: /var/www
      volumes:
        - ./app-frontend:/var/www
      networks:
        - app-network
  

    backend:
      build:
        context: ./app-backend/
      restart: always
      environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
      working_dir: /var/www
      volumes:
        - ./app-backend:/var/www
      networks:
        - app-network
        - db-network

    appdb:
      image: mysql:5.7
      restart: always
      volumes:
        - ./db_data:/var/lib/mysql
      environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
      networks:
        - db-network

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      environment:
        PMA_HOST: appdb
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      depends_on:
        - appdb
      ports:
        - 8443:80
      networks:
        - db-network

networks:
  app-network:
    driver: bridge
  db-network: