version: '3.7'

services:
    frontend:
      build:
        context: ./frontend
      restart: always
      ports:
        - "3000:3000"
      working_dir: /var/www
      volumes:
        - ./frontend:/var/www
      networks:
        - app-network

    backend:
      build:
        context: ./backend
      restart: always
      environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
      working_dir: /var/www
      volumes:
        - ./backend:/var/www
      networks:
        - app-network
        - db-network
      depends_on:
        - database

    database:
      image: mysql:5.7
      container_name: appdb
      restart: always
      volumes:
        - ./db_data:/var/lib/mysql
      environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
      networks:
        - db-network

networks:
  app-network:
    driver: bridge
  db-network: