version: '3.7'

services:
    frontend:
      platform: linux/x86_64
      build:
        context: ./frontend
      container_name: frontend
      restart: always
      ports:
        - "3000:3000"
      volumes:
        - ./frontend:/app
        - /app/node_modules
      networks:
        - app-network

    backend:
      platform: linux/x86_64
      build:
        args:
          user: ubuntu
          uid: 1000
        context: ./backend
      container_name: backend
      restart: always
      environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
      volumes:
        - ./backend:/app
        - /app/vendor
      networks:
        - app-network
      ports:
        - "8000:8000"
      depends_on:
        - database

    database:
      platform: linux/x86_64
      image: mysql:5.7
      container_name: database
      restart: always
      volumes:
        - ./db_data:/var/lib/mysql
      environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
      networks:
        - app-network

networks:
  app-network:
    driver: bridge