export const categoryTypes = {
  FETCH_CATEGORIES_REQUEST: 'FETCH_CATEGORIES_REQUEST',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  REGISTRATION_REQUEST: 'REGISTRATION_REQUEST',
  FETCH_PROFILE_REQUEST: 'FETCH_PROFILE_REQUEST',
  FETCH_PROFILE_WITH_REDIRECT_REQUEST: 'FETCH_PROFILE_WITH_REDIRECT_REQUEST',
  CHECK_AUTHENTICATION: 'CHECK_AUTHENTICATION',
}

const allTypes = {
  categoryTypes
}

export default allTypes
